import jwt

login_token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3MjM3MTIxNCwianRpIjoiMDk2Mzg3ZWItZDU2Zi00ODI5LTlkNzktMjBlMjBiNmJkMjkyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJpZCI6MSwicm9sZSI6Imxhd3llciJ9LCJuYmYiOjE3NzIzNzEyMTQsImNzcmYiOiI5OGE5ZmY1ZS1iMzRjLTRlMmMtOTA4MC1jZTZmNWEyYzMzMGYiLCJleHAiOjE3NzIzNzQ4MTR9.-Hy2vARxSY31AXJyvt5RLLReiwNVqom7w6TxPxTI1bM'
print(jwt.decode(login_token, 'test-secret', algorithms=['HS256']))
