"""autogenerate models

Revision ID: 953ca689a088
Revises:
Create Date: 2026-02-24 18:00:51.572240

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "953ca689a088"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

    op.create_table(
        "case",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("assigned_judge_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_judge_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=255), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "otp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("usage", sa.JSON(), nullable=True),
        sa.Column("feature_used", sa.String(length=100), nullable=True),
        sa.Column("ip_address", sa.String(length=100), nullable=True),
        sa.Column("token_usage", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=255), nullable=True),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=120), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hearing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("hearing_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("provider_ref", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Note: autogenerate detected existing/removed tables in the target DB.
    # To avoid destructive operations against an existing schema (foreign key
    # constraints may prevent drops), we intentionally skip drop operations here.
    # ### end Alembic commands ###


def downgrade():
    # reverse of upgrade: simply drop tables in reverse order of creation
    op.drop_table("payment")
    op.drop_table("hearing")
    op.drop_table("document")
    op.drop_table("audit_log")
    op.drop_table("ai_log")
    op.drop_table("otp")
    op.drop_table("notification")
    op.drop_table("case")
    op.drop_table("user")

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("uploaded_by", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("documents_ibfk_1"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("documents_ibfk_2"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_documents_case"), ["case_id"], unique=False
        )

    op.create_table(
        "hearings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("hearing_date", sa.DateTime(), nullable=False),
        sa.Column("judge_id", sa.Integer(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("next_hearing_date", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("hearings_ibfk_1"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("hearings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_hearings_date"), ["hearing_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_hearings_case"), ["case_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_hearings_judge"), ["judge_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("hearings_ibfk_2"),
            "users",
            ["judge_id"],
            ["id"],
            ondelete="SET NULL",
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("users_ibfk_1"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_users_role"), ["role_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_users_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("email"), ["email"], unique=True)

    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_number", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("case_type", sa.String(length=100), nullable=True),
        sa.Column(
            "court_level",
            sa.Enum("District", "High", "Supreme", name="court_level_enum"),
            server_default=sa.text("'District'"),
            nullable=True,
        ),
        sa.Column(
            "financial_amount", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column(
            "complexity_score", sa.Integer(), autoincrement=False, nullable=True
        ),
        sa.Column("filed_by", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "assigned_judge", sa.Integer(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "assigned_lawyer", sa.Integer(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum("Pending", "Active", "Closed", "Appealed", name="case_status_enum"),
            server_default=sa.text("'Pending'"),
            nullable=True,
        ),
        sa.Column(
            "priority",
            sa.Enum("Low", "Medium", "High", name="case_priority_enum"),
            server_default=sa.text("'Medium'"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_judge"],
            ["users.id"],
            name=op.f("cases_ibfk_2"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_lawyer"],
            ["users.id"],
            name=op.f("cases_ibfk_3"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["filed_by"], ["users.id"], name=op.f("cases_ibfk_1"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_cases_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("idx_cases_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_cases_lawyer"), ["assigned_lawyer"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_cases_judge"), ["assigned_judge"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_cases_filed_by"), ["filed_by"], unique=False
        )
        batch_op.create_index(batch_op.f("case_number"), ["case_number"], unique=True)

    op.create_table(
        "case_status_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("old_status", sa.String(length=50), nullable=True),
        sa.Column("new_status", sa.String(length=50), nullable=True),
        sa.Column("changed_by", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "changed_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
            name=op.f("case_status_history_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("case_status_history_ibfk_2"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("payment")
    op.drop_table("hearing")
    op.drop_table("document")
    op.drop_table("audit_log")
    op.drop_table("ai_log")
    op.drop_table("otp")
    op.drop_table("notification")
    op.drop_table("case")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    # ### end Alembic commands ###